export default {
  floatPrecision: 4,
  multipass: true,
  plugins: [
    "cleanupAttrs",
    "removeDoctype",
    "removeXMLProcInst",
    "removeComments",
    "removeMetadata",
    "removeTitle",
    "removeDesc",
    "removeUselessDefs",
    "removeEditorsNSData",
    "removeEmptyAttrs",
    "removeHiddenElems",
    "removeEmptyText",
    "removeViewBox",
    "cleanupEnableBackground",
    "minifyStyles",
    "convertStyleToAttrs",
    "convertColors",
    "convertPathData",
    "convertTransform",
    "removeUnknownsAndDefaults",
    "removeNonInheritableGroupAttrs",
    {
      name: "removeUselessStrokeAndFill",
      params: {
        // https://github.com/svg/svgo/issues/727#issuecomment-303115276
        removeNone: true,
      },
    },
    "removeUnusedNS",
    "cleanupIds",
    "cleanupNumericValues",
    "cleanupListOfValues",
    "moveElemsAttrsToGroup",
    "moveGroupAttrsToElems",
    "collapseGroups",
    "removeRasterImages",
    "mergePaths",
    "convertShapeToPath",
    "sortAttrs",
    "removeDimensions",
    "removeElementsByAttr",
    "removeStyleElement",
    "removeScriptElement",
    "removeEmptyContainers",
  ],
};
